title: "ment"
description: "local llms on apple devices"
# Adjust these as needed:
url: "https://spenceros.github.io"
baseurl: "/ment.tools"
# If you want GitHub Pages to build with Jekyll:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Where Jekyll will look for your posts (used by news.html)
collections:
  posts:
    output: true

theme: null

# Optional: Exclude or include certain files
exclude:
  - "node_modules"
  - "README.md"
  - ".gitignore"